services:
  - type: web
    name: patrapayal
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: pythonfullstack
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn library:app --bind 0.0.0.0:$PORT
