services:
  - type: web
    name: library-management-system
    env: python
    buildCommand: "pip install -r requirements.txt && python database/init_db.py"
    startCommand: "gunicorn library:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production
